server:
  port: 10086
spring:
  application:
    name: mq-rabbitmq-producer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: fwx
    password: 123456
    virtualHost: fwx
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: topic.exchange
    publisher-confirm-type: correlated